GET http://localhost:3000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtIiwiaWF0IjoxNjQ0NDczMDg4LCJleHAiOjE2NDQ0NzMxMTh9.wj06nCeZZDn4NpR629XkEIkOjArjhoC3DAnSV0-2LYU
####


POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"sam"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtIiwiaWF0IjoxNjQ0NDczMDA3fQ.8Bouf1K-_2wV4lkwSJvh8MyuP6UWoWsNpmcUs2grDpM"
}